### ISSUE TITLE
Handle finding of nested resources

### ISSUE THREAD

**Issue by olliebennett** [jcypret/hashid-rails#3]
Suppose my routes are as follows:

``` ruby
resources :posts do
    resources :comments
end
```

That is to say, a `Comment` is _nested_ below the `Post` resource.

I have the following URL for viewing a comment on its own page:

```
/posts/ABC/comments/XYZ
```

The following works perfectly:

``` ruby
@post = Post.find(params[:post_id])
```

However, when attempting to retrieve a specific comment, based on the post:

``` ruby
@post = Post.find(params[:post_id])
@comment = Post.comments.find(params[:id])
```

I see the following error:

```
ActiveRecord::RecordNotFound at /posts/ABC/comments/XYZ
Couldn't find Comment with 'id'=XYZ [WHERE "comments"."post_id" = 123]
- - -
SELECT  "comments".* FROM "comments" WHERE "comments"."post_id" = $1 AND "comments"."id" = $2 LIMIT 1  [["post_id", 123], ["id", 0]]
```

Another attempt was the following:

```
@comment = Comment.where(post: @post).find(params[:id])
```

which errored with:

```
Couldn't find Comment with 'id'=XYZ [WHERE "comments"."post_id" = 123]
- - -
SELECT  "comments".* FROM "comments" WHERE "comments"."post_id" = 123 AND "comments"."id" = $1 LIMIT 1  [["id", 0]]
```

Note that in each case the ID is `0` because I'm passing the HashID which is converted to the integer `0`.

It would be great to support this without requiring me to refactor my code and manually handle the HashID <--> ID conversion. Any thoughts?

**Comment by olliebennett** [comment]
Related problem for Obfuscate IDs: https://github.com/namick/obfuscate_id/issues/44

**Comment by jcypret** [comment]
@olliebennett Sorry for the delayed response! I didn't realize I was getting notifications for this repo. That's definitely an issue I'd like to work out. I'll can block out some time to work on a solution, or if you'd like to try a pull request, you're more than welcome. Let me know either way. Thanks!

**Comment by dtaniwaki** [comment]
Hi @jcypret 
I solved the issue in my own gem with this.
https://github.com/dtaniwaki/acts_as_hashids/blob/09e1b379c22ba6a6ace5677a403e0f144af94cdf/lib/acts_as_hashids/core.rb#L52

You can extend `has_many` with your custom `find`. Hope it's helpful in your case.

**Comment by SirRawlins** [comment]
This would definitely be a great feature to have, I scope nearly all my queries through a single top level model. I.e. `Foo.find(1).bars.find('qJ5YM5Lp')`

@dtaniwaki as an aside I just tried your gem and it doesn't appear this functionality works - are you sure it should? If so I'll open an issue.

**Comment by jcypret** [comment]
@SirRawlins That functionality doesn't currently work on master. Working on a new version in the `sign-hashids` branch that resolves this as well as a few other minor issues. Hoping to have a new release this week. You're welcome to give the branch a try. 

That branch removes including it in all models. You instead include it select models using: `include Hashid::Rails`.

**Comment by SirRawlins** [comment]
@jcypret sounds awesome. I'll give that a try, thanks so much.

**Comment by jcypret** [comment]
This has been resolved in the latest release. Specs have been added to exercise associations: https://github.com/jcypret/hashid-rails/blob/49ba2f9126f0daea292974a62a66bb3c25aee825/spec/hashid/rails_spec.rb#L31

**Comment by SirRawlins** [comment]
@jcypret finally got around to dropping this in today and even running `1.0.0` I'm still getting the same error when running `association.find(params[:hash_id])` - I am able to use `association.find_by_hashid()` as a work around, but it's less than ideal.

I'm wondering if your test case is giving a false-positive, I wonder if it should be using `comment.to_param` instead of `comment.id`?

https://github.com/jcypret/hashid-rails/blob/49ba2f9126f0daea292974a62a66bb3c25aee825/spec/hashid/rails_spec.rb#L36

**Comment by jemminger** [comment]
@jcypret I'm still seeing this issue on 1.2.1

**Comment by jemminger** [comment]
@jcypret @SirRawlins Scratch that, I think the issue arises when the parent model does not have hashids enabled.  Adding Hashids::Rails to both the parent and child models works as expected.

**Comment by jtoy** [comment]
just ran into the same issue, I think it should be in the readme.
@jemminger and all, doesnt make sense to me that you need to include hashid into models that dont use it but you need it for their associations.

**Comment by AlphonseSantoro** [comment]
I can't seem to get find all to work. I have a form where I post the hashids  ( model_ids: [hashids...] ). 
However when I post this form I get this error:
Couldn't find all Model with 'id': (0, 0, 0) (found 0 results, but was looking for 3)
This works fine when passing normal ids
